# Porta em que o servidor local vai rodar.
server.port=8080

# Nome da aplicacao
spring.application.name=streaming

# Biblioteca de midia local
streaming.media.library-path=C:/Users/felip/Downloads/Streaming-MP4

# Extensoes de arquivo que a aplicacao vai reconhecer como midia
streaming.media.allowed-extensions=mp4,mkv,avi,mov

#Banco H2
spring.datasource.url=jdbc:h2:file:./data/streaming
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=